git:
  pagers:
    - colorArg: always
gui:
  border: single
  mainPanelSplitMode: horizontal
  nerdFontsVersion: "3"
  sidePanelWidth: 0.25
  showListFooter: false
  showNumstatInFilesView: true
  showRandomTip: false
keybinding:
  commits:
    copyCommitAttributeToClipboard: "<c-o>"
  files:
    copyFileInfoToClipboard: "<c-o>"
  universal:
    copyToClipboard: y
    prevItem: k
    submitEditorText: "<c-s>"
    nextItem: j
    prevPage: <disabled>
    nextPage: <disabled>
    prevBlock: ","
    nextBlock: "."
os:
  editPreset: nvim
promptToReturnFromSubprocess: false
update:
  method: never
